# Generated by Django 3.1.5 on 2021-03-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('webapp', '0009_auto_20210317_0838'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.propertydetails')),
            ],
        ),
    ]
