# Generated by Django 3.1.5 on 2021-03-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profile_picture',
            field=models.ImageField(default='profile.png', upload_to='profile_pictures'),
        ),
    ]
