# Generated by Django 3.1.5 on 2021-03-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210318_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
