# Generated by Django 3.1.5 on 2021-03-07 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('land', 'Land')], max_length=7, verbose_name='Type')),
                ('property_option', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], max_length=7, verbose_name='Category')),
                ('property_title', models.CharField(help_text='Example- House for Sale in Kathmandy', max_length=200)),
                ('main_image', models.ImageField(upload_to='image')),
                ('image2', models.ImageField(help_text='A clear image showing the whole property.', upload_to='image')),
                ('image3', models.ImageField(upload_to='image')),
                ('image4', models.ImageField(upload_to='image')),
                ('property_description', models.TextField()),
                ('price', models.IntegerField()),
                ('negotiable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
