# Generated by Django 3.1.5 on 2021-03-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='image2',
            field=models.ImageField(blank=True, help_text='A clear image showing the whole property.', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='image3',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='image4',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_description',
            field=models.TextField(blank=True),
        ),
    ]
