# Generated by Django 3.1.5 on 2021-03-07 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210307_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
