# Generated by Django 3.1.5 on 2021-03-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_propertydetails_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='Province',
            field=models.CharField(choices=[('1', 'Province1'), ('2', 'Province2'), ('3', 'Bagmati'), ('4', 'Gandaki'), ('5', 'Lumbini'), ('6', 'Karnali'), ('7', 'Sudurpashchim')], default='Bagmati', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='address',
            field=models.CharField(default='Kathmandu', max_length=100),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
