# Generated by Django 3.1.5 on 2021-03-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210308_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_option',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=7, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Land', 'Land')], max_length=7, verbose_name='Type'),
        ),
    ]
