# Generated by Django 3.1.5 on 2021-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='unpublish',
        ),
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
