# Generated by Django 3.1.5 on 2021-03-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210315_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='image2',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='main_image',
            field=models.ImageField(help_text='A clear image showing the whole property.', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_title',
            field=models.CharField(max_length=200),
        ),
    ]
